from odoo.addons.spec_driven_model.hooks import post_init_hook as spec_post_init_hook


def post_init_hook(cr, registry):
    # add permissions to models generated by spec_driven_model
    spec_post_init_hook(cr, registry, 'odoo.addons.l10n_mx_cfdi', 'odoo.addons.l10n_mx_cfdi_spec.models.mixin.cfdv40')
